# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0005_auto_20170721_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorrole',
            old_name='authors',
            new_name='author',
        ),
    ]
