# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0007_auto_20170721_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcm.Role'),
        ),
    ]
