# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('mcm', '0010_auto_20170721_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('order', models.IntegerField()),
                ('description', models.TextField(default='', verbose_name='description')),
                ('copyright', models.CharField(max_length=200, verbose_name='copyright')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('doc_type', models.CharField(max_length=16, verbose_name='document type')),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('screen_image_width', models.IntegerField()),
                ('screen_image_height', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcm.Document')),
                ('original_file', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_image', to='filer.Image')),
                ('screen_file', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screen_image', to='filer.Image')),
            ],
        ),
    ]
