# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0011_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('a', 'Notice spectacle'), ('b', 'Disque'), ('c', 'Vid\xe9o DVD&VHS'), ('d', 'Vid\xe9o en ligne'), ('e', 'Site Internet'), ('f', 'Ouvrage & Th\xe8se'), ('g', 'Revue'), ('h', 'Article'), ('i', 'Photo'), ('j', 'Affiche - Brochure'), ('k', 'P\xe9dagogique'), ('l', 'Objet')], max_length=32, verbose_name='document type'),
        ),
    ]
