# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0020_auto_20170913_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'collection',
            },
        ),
        migrations.CreateModel(
            name='EditedDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mcm.Document')),
                ('edition_place', models.CharField(max_length=100, verbose_name='edition_place')),
                ('collection', models.ManyToManyField(to='mcm.Collection', verbose_name='collection')),
            ],
            bases=('mcm.document',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'language',
            },
        ),
        migrations.AddField(
            model_name='editeddocument',
            name='language',
            field=models.ManyToManyField(to='mcm.Language', verbose_name='language'),
        ),
        migrations.AddField(
            model_name='object',
            name='collection',
            field=models.ManyToManyField(to='mcm.Collection', verbose_name='collection'),
        ),
    ]
