# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'H - Article', 'verbose_name_plural': 'H - Articles'},
        ),
        migrations.AlterModelOptions(
            name='authorrole',
            options={'verbose_name': 'author role'},
        ),
        migrations.AlterModelOptions(
            name='bookthesis',
            options={'verbose_name': 'F - Ouvrage & Th\xe8se', 'verbose_name_plural': 'F - Ouvrages & Th\xe8ses'},
        ),
        migrations.AlterModelOptions(
            name='disc',
            options={'verbose_name': 'B - Disque', 'verbose_name_plural': 'B - Disques'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'G - Revue', 'verbose_name_plural': 'G - Revues'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'A - Notice spectacle', 'verbose_name_plural': 'A - Notices spectacle'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'L - Objet', 'verbose_name_plural': 'L-Objets'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'I - Photo', 'verbose_name_plural': 'I - Photos'},
        ),
        migrations.AlterModelOptions(
            name='posterbooklet',
            options={'verbose_name': 'J - Affiche-Brochure', 'verbose_name_plural': 'J - Affiches-Brochures'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'C - Vid\xe9o DVD&VHS', 'verbose_name_plural': 'C - Vid\xe9os DVD&VHS'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'verbose_name': 'D - Vid\xe9o en ligne', 'verbose_name_plural': 'D - Vid\xe9os en ligne'},
        ),
        migrations.AddField(
            model_name='author',
            name='old_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
