# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-20 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0003_auto_20170720_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bookthesis',
            name='code',
        ),
        migrations.RemoveField(
            model_name='disc',
            name='code',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='code',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='code',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='code',
        ),
        migrations.RemoveField(
            model_name='posterbooklet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='video',
            name='code',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='code',
        ),
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, max_length=200, verbose_name='code'),
        ),
    ]
