# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0004_auto_20170721_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='indexation_date',
        ),
        migrations.AddField(
            model_name='notice',
            name='doc_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='document source'),
        ),
        migrations.AddField(
            model_name='notice',
            name='release_date_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='release date'),
        ),
    ]
