# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0008_auto_20170721_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='text'),
        ),
    ]
