# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0013_auto_20170908_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='archive_dvd',
            field=models.CharField(blank=True, max_length=200, verbose_name='DVD archive'),
        ),
    ]
