# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0014_photo_archive_dvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='indexation_date',
            field=models.DateField(blank=True, null=True, verbose_name='indexation date'),
        ),
        migrations.AddField(
            model_name='notice',
            name='indexation_date_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='indexation date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='archive_dvd',
            field=models.CharField(max_length=200, verbose_name='DVD archive'),
        ),
    ]
