# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0016_auto_20170908_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='old_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
