# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0017_auto_20170908_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='old_doc_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
