# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0018_document_old_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copyright_text',
            field=models.CharField(default='', max_length=250, verbose_name='copyright'),
        ),
    ]
