# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcm', '0019_document_copyright_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
